replicaCount: 1
agentsPerPod: 10
proxyServer: ""
authServer: ""

minReadySeconds: 0

image:
  repository: public.ecr.aws/gravitational/teleport
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true
  roleARN:

joinParams:
  method: token
  token_name: qwertyuiop

podMonitor:
  enabled: true
  interval: 30s

databases: []

tolerations: []

affinity: {}