apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  teleport.yaml: |2
    version: v3
    teleport:
      log:
        severity: DEBUG
      storage:
        type: dir
      {{- if .Values.authServer }}
      auth_server: {{ .Values.authServer }}
      {{- end }}
      {{- if .Values.proxyServer }}
      proxy_server: {{ .Values.proxyServer }}
      {{- end }}
      join_params: {{- toYaml .Values.joinParams | nindent 8 }}
    auth_service:
      enabled: false
    proxy_service:
      enabled: false
    ssh_service:
      enabled: false
    db_service:
      enabled: yes
      databases: {{- toYaml .Values.databases | nindent 8 }}
  entrypoint.sh: |2
    #!/bin/bash
    set -euxo pipefail
    cp /etc/teleport-config/teleport.yaml /etc/teleport.yaml
    exec teleport start -c /etc/teleport.yaml --diag-addr=0.0.0.0:3000
