{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn:  {{ .Values.serviceAccount.roleARN }}
{{- end }}
